name: Playwright Tests

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./playwright

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          CI: true
          WEB_URL: ${{ vars.WEB_URL }}
          API_URL: ${{ vars.API_URL }}
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-results-${{ github.run_id }}
          path: |
            playwright/playwright-report/
            playwright/test-results.json
          retention-days: 30

      - name: Setup Pages
        if: ${{ !cancelled() }}
        uses: actions/configure-pages@v5

      - name: Upload report to Pages
        if: ${{ !cancelled() }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy report
        if: ${{ !cancelled() }}
        uses: actions/deploy-pages@v4
